// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ockbibrzqfifchizrzgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ja2JpYnJ6cWZpZmNoaXpyemdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTkwMTUsImV4cCI6MjA3Mzc3NTAxNX0.Q4H-Z1VZ_ZsnYjSJBu11_1o1XtkzrxjB6-vuVNxLwSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'her'
  }
});